In [3]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [ ]:
#pip install imblearn

In [4]:
pd.set_option('display.max_columns', None)       # shows all cols / rows
pd.set_option('display.max_rows', None)

In [5]:
df = pd.read_csv('fin_risk_data.csv')
df.head()

Unnamed: 0  Age  Estimated Income  Superannuation Savings  \
0           0   24          75384.77                17677.95   
1           1   23         289834.31                17398.92   
2           2   27         169935.23                42825.90   
3           3   40         356808.11                 5473.15   
4           4   46         130711.68                48077.60   

   Amount of Credit Cards  Credit Card Balance  Bank Loans  Bank Deposits  \
0                       1               484.54   776242.92     1485828.64   
1                       1              2256.88  1270615.43      641482.79   
2                       2              4568.74  1052715.84     1033401.59   
3                       2              4205.00   121195.06     1048157.49   
4                       1              3779.49  1048301.95      487782.53   

   Checking Accounts  Saving Accounts  Foreign Currency Account  \
0          603617.88        607332.46                  12249.96   
1          229521.37        344635.16                  61162.31   
2          652674.69        203054.35                  79071.78   
3         1048157.49        234685.02                  57513.65   
4          446644.25        128351.45                  30012.14   

   Business Lending  Properties Owned  Risk Weighting  BRId  GenderId  IAId  \
0        1134475.30                 1               2     1         1     1   
1        2000526.10                 1               3     2         1     2   
2         548137.58                 1               3     3         2     3   
3        1148402.29                 0               4     4         1     4   
4        1674412.12                 0               3     1         2     5   

   Nationality_African  Nationality_American  Nationality_Asian  \
0                    0                     1                  0   
1                    1                     0                  0   
2                    0                     0                  0   
3                    0                     1                  0   
4                    0                     1                  0   

   Nationality_Australian  Nationality_European  Fee Structure_High  \
0                       0                     0                   1   
1                       0                     0                   1   
2                       0                     1                   1   
3                       0                     0                   0   
4                       0                     0                   0   

   Fee Structure_Low  Fee Structure_Mid  Loyalty Classification_Gold  \
0                  0                  0                            0   
1                  0                  0                            0   
2                  0                  0                            1   
3                  0                  1                            0   
4                  0                  1                            0   

   Loyalty Classification_Jade  Loyalty Classification_Platinum  \
0                            1                                0   
1                            1                                0   
2                            0                                0   
3                            0                                0   
4                            0                                1   

   Loyalty Classification_Silver  Income Band_Low  Income Band_Mid  \
0                              0                1                0   
1                              0                0                1   
2                              0                0                1   
3                              1                0                0   
4                              0                0                1   

   Income Band_High  
0                 0  
1                 0  
2                 0  
3                 1  
4                 0

In [6]:
df = df.drop('Unnamed: 0', axis=1)

In [6]:
df.head(2)

Age  Estimated Income  Superannuation Savings  Amount of Credit Cards  \
0   24          75384.77                17677.95                       1   
1   23         289834.31                17398.92                       1   

   Credit Card Balance  Bank Loans  Bank Deposits  Checking Accounts  \
0               484.54   776242.92     1485828.64          603617.88   
1              2256.88  1270615.43      641482.79          229521.37   

   Saving Accounts  Foreign Currency Account  Business Lending  \
0        607332.46                  12249.96         1134475.3   
1        344635.16                  61162.31         2000526.1   

   Properties Owned  Risk Weighting  BRId  GenderId  IAId  \
0                 1               2     1         1     1   
1                 1               3     2         1     2   

   Nationality_African  Nationality_American  Nationality_Asian  \
0                    0                     1                  0   
1                    1                     0                  0   

   Nationality_Australian  Nationality_European  Fee Structure_High  \
0                       0                     0                   1   
1                       0                     0                   1   

   Fee Structure_Low  Fee Structure_Mid  Loyalty Classification_Gold  \
0                  0                  0                            0   
1                  0                  0                            0   

   Loyalty Classification_Jade  Loyalty Classification_Platinum  \
0                            1                                0   
1                            1                                0   

   Loyalty Classification_Silver  Income Band_Low  Income Band_Mid  \
0                              0                1                0   
1                              0                0                1   

   Income Band_High  
0                 0  
1                 0

In [7]:
df['Risk Weighting'].value_counts()

2    1222
1     836
3     460
4     322
5     160
Name: Risk Weighting, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Age                              3000 non-null   int64  
 1   Estimated Income                 3000 non-null   float64
 2   Superannuation Savings           3000 non-null   float64
 3   Amount of Credit Cards           3000 non-null   int64  
 4   Credit Card Balance              3000 non-null   float64
 5   Bank Loans                       3000 non-null   float64
 6   Bank Deposits                    3000 non-null   float64
 7   Checking Accounts                3000 non-null   float64
 8   Saving Accounts                  3000 non-null   float64
 9   Foreign Currency Account         3000 non-null   float64
 10  Business Lending                 3000 non-null   float64
 11  Properties Owned                 3000 non-null   int64  
 12  Risk Weighting      

In [9]:
df.shape

(3000, 31)

In [10]:
#creating X & Y variables

x = df.drop('Risk Weighting', axis=1)
x.head(3)

Age  Estimated Income  Superannuation Savings  Amount of Credit Cards  \
0   24          75384.77                17677.95                       1   
1   23         289834.31                17398.92                       1   
2   27         169935.23                42825.90                       2   

   Credit Card Balance  Bank Loans  Bank Deposits  Checking Accounts  \
0               484.54   776242.92     1485828.64          603617.88   
1              2256.88  1270615.43      641482.79          229521.37   
2              4568.74  1052715.84     1033401.59          652674.69   

   Saving Accounts  Foreign Currency Account  Business Lending  \
0        607332.46                  12249.96        1134475.30   
1        344635.16                  61162.31        2000526.10   
2        203054.35                  79071.78         548137.58   

   Properties Owned  BRId  GenderId  IAId  Nationality_African  \
0                 1     1         1     1                    0   
1                 1     2         1     2                    1   
2                 1     3         2     3                    0   

   Nationality_American  Nationality_Asian  Nationality_Australian  \
0                     1                  0                       0   
1                     0                  0                       0   
2                     0                  0                       0   

   Nationality_European  Fee Structure_High  Fee Structure_Low  \
0                     0                   1                  0   
1                     0                   1                  0   
2                     1                   1                  0   

   Fee Structure_Mid  Loyalty Classification_Gold  \
0                  0                            0   
1                  0                            0   
2                  0                            1   

   Loyalty Classification_Jade  Loyalty Classification_Platinum  \
0                            1                                0   
1                            1                                0   
2                            0                                0   

   Loyalty Classification_Silver  Income Band_Low  Income Band_Mid  \
0                              0                1                0   
1                              0                0                1   
2                              0                0                1   

   Income Band_High  
0                 0  
1                 0  
2                 0

In [11]:
y = df['Risk Weighting']
y.head(3)

0    2
1    3
2    3
Name: Risk Weighting, dtype: int64

In [12]:
# checking if data is balanced in %

y.value_counts(normalize=True)*100

2    40.733333
1    27.866667
3    15.333333
4    10.733333
5     5.333333
Name: Risk Weighting, dtype: float64

In [13]:
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [14]:
y_test.shape

(600,)

# Decision Tree Classifier

In [13]:
model_dt = DecisionTreeClassifier(criterion='gini', random_state=100, max_depth=6,min_samples_leaf=8)
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [14]:
y_pred = model_dt.predict(x_test)
y_pred

array([2, 2, 1, 2, 2, 1, 2, 4, 2, 4, 5, 1, 1, 2, 1, 1, 2, 2, 4, 2, 2, 2,
       2, 3, 2, 2, 4, 2, 1, 1, 3, 2, 2, 1, 2, 1, 1, 3, 1, 2, 1, 2, 1, 2,
       4, 4, 1, 2, 1, 2, 4, 1, 2, 1, 1, 1, 2, 2, 1, 2, 3, 1, 2, 2, 3, 3,
       2, 1, 4, 2, 2, 2, 2, 2, 2, 3, 2, 3, 5, 1, 2, 2, 1, 1, 2, 4, 2, 2,
       2, 2, 1, 2, 1, 5, 2, 3, 2, 2, 3, 1, 2, 4, 2, 2, 1, 2, 2, 2, 1, 2,
       5, 1, 1, 1, 4, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2,
       2, 4, 3, 2, 1, 2, 2, 2, 3, 1, 1, 2, 1, 2, 3, 3, 3, 2, 2, 3, 1, 2,
       2, 2, 4, 2, 1, 1, 3, 2, 2, 3, 1, 4, 1, 1, 2, 2, 4, 4, 2, 3, 2, 2,
       2, 1, 4, 3, 2, 3, 2, 1, 3, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2,
       1, 2, 2, 2, 1, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 1, 2, 2, 2,
       3, 2, 2, 3, 2, 2, 2, 3, 2, 2, 4, 1, 1, 1, 2, 5, 2, 2, 2, 2, 2, 2,
       2, 2, 5, 1, 2, 3, 3, 2, 3, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 3, 3, 2, 2, 2, 1, 5, 1, 2, 2, 1, 2, 1, 2, 1, 1,
       1, 2, 3, 2, 2, 1, 4, 2, 3, 1, 3, 2, 3, 2, 1,

In [23]:
print(type(y_pred))
print(y_pred.shape)   # == y_test.shape?
print(y_pred[:10])

<class 'numpy.ndarray'>
(600,)
[2 2 1 2 2 1 2 4 2 4]


In [24]:
print(type(y_test))
print(y_test.shape)   # == y_test.shape?
print(y_test[:10])

<class 'pandas.core.series.Series'>
(600,)
1270    1
1298    2
1853    1
2189    3
865     4
1123    1
1236    2
2978    3
783     2
1110    4
Name: Risk Weighting, dtype: int64


In [15]:
# Compairing predicted values with actual ones

model_dt.score(x_test, y_pred)

1.0

In [27]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.80      0.74      0.76       174

   micro avg       0.80      0.74      0.76       174
   macro avg       0.40      0.37      0.38       174
weighted avg       0.80      0.74      0.76       174



C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classif

In [28]:
print(confusion_matrix(y_test, y_pred))

[[128  45   0   1   0]
 [ 32 177  19  10   0]
 [  1  47  39  10   0]
 [  0  17  25  18   3]
 [  0   5   9  10   4]]


### NOTE:

# Over-Sampling

In [25]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)

In [26]:
xr_train,xr_test, yr_train, yr_test = train_test_split(X_resampled,y_resampled, test_size=0.2)

In [27]:
model_dt_smote = DecisionTreeClassifier(criterion='gini', random_state=100, max_depth=6,min_samples_leaf=8)

In [28]:
model_dt_smote.fit(xr_train,yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [29]:
y_pred_smote = model_dt_smote.predict(xr_test)

In [30]:
print(classification_report(yr_test, y_pred_smote, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.90      0.95      0.92       164

   micro avg       0.90      0.95      0.92       164
   macro avg       0.45      0.47      0.46       164
weighted avg       0.90      0.95      0.92       164



C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classif

In [31]:
print(confusion_matrix(yr_test, y_pred_smote))

[[155   2   1   6   0]
 [ 13   4   9   3   1]
 [  3   4  48  39  31]
 [  1   4  33  71  54]
 [  1   0  28  48 134]]


In [32]:
print(type(y_test))
print(y_test.shape)   # == y_test.shape?
print(y_test[:10])

<class 'pandas.core.series.Series'>
(600,)
1270    1
1298    2
1853    1
2189    3
865     4
1123    1
1236    2
2978    3
783     2
1110    4
Name: Risk Weighting, dtype: int64


In [33]:
print(type(y_pred_smote))
print(y_pred_smote.shape)   # == y_test.shape?
print(y_pred_smote[:10])

<class 'numpy.ndarray'>
(693,)
[3 3 1 4 5 4 4 3 5 3]


In [34]:
# decision tree not really performing well

# Random Forest Classifier

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
model_rf = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6,min_samples_leaf=8)
model_rf.fit(x_train,y_train)
y_pred_rf = model_rf.predict(x_test)

In [44]:
print(classification_report(y_test, y_pred_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.81      0.71      0.76       178

   micro avg       0.81      0.71      0.76       178
   macro avg       0.41      0.36      0.38       178
weighted avg       0.81      0.71      0.76       178



C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classif

In [52]:
print(type(y_test))
print(y_test.shape)   # == y_test.shape?
print(y_test[:10])

print('-'*50)

print(type(y_pred_rf))
print(y_pred_rf.shape)   # == y_test.shape?
print(y_pred_rf[:10])

<class 'pandas.core.series.Series'>
(600,)
1270    1
1298    2
1853    1
2189    3
865     4
1123    1
1236    2
2978    3
783     2
1110    4
Name: Risk Weighting, dtype: int64
--------------------------------------------------
<class 'numpy.ndarray'>
(600,)
[2 2 1 2 2 1 2 2 2 4]


In [45]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)

In [46]:
xr_train,xr_test, yr_train, yr_test = train_test_split(X_resampled,y_resampled, test_size=0.2)

In [47]:
model_rf_smote = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6,min_samples_leaf=8)
model_rf_smote.fit(xr_train,yr_train)
y_pred_smote_rf = model_rf_smote.predict(xr_test)

In [48]:
print(classification_report(yr_test, y_pred_smote_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.91      0.96      0.93       152

   micro avg       0.91      0.96      0.93       152
   macro avg       0.45      0.48      0.47       152
weighted avg       0.91      0.96      0.93       152



C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classif

In [49]:
print(confusion_matrix(yr_test, y_pred_smote_rf))

[[146   0   0   4   2]
 [  9   2   4   8   5]
 [  4   0  32  53  51]
 [  2   1   1 108  51]
 [  0   0   2  17 190]]


In [51]:
print(type(y_test))
print(y_test.shape)   # == y_test.shape?
print(y_test[:10])

print('-'*50)

print(type(y_pred_smote_rf))
print(y_pred_smote_rf.shape)   # == y_test.shape?
print(y_pred_smote_rf[:10])

<class 'pandas.core.series.Series'>
(600,)
1270    1
1298    2
1853    1
2189    3
865     4
1123    1
1236    2
2978    3
783     2
1110    4
Name: Risk Weighting, dtype: int64
--------------------------------------------------
<class 'numpy.ndarray'>
(692,)
[4 5 5 5 5 3 5 5 5 4]


# SAVING MODEL

In [ ]:
# This ensures time saving by letting us directly call the model and 
# perform predictions on unseen data (*without Re-Running model each & everytime*)

In [76]:
import pickle

In [77]:
filename = 'model.sav'

In [78]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [81]:
load_model = pickle.load(open(filename, 'rb'))   #checking if saved model is working fine
load_model.score(xr_test,yr_test)

0.9357326478149101

# PCA: (could be performed if accuracy is still not good)

In [37]:
from sklearn.decomposition import PCA

pca = PCA(0.9)
xr_train1 = pca.fit_transform(x_train, y_train)

In [38]:
xr_test1 = pca.transform(x_test)

In [39]:
model_pca = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6,min_samples_leaf=8)
model_pca.fit(x_train,y_train)
y_pred_pca = model_pca.predict(x_test)

In [40]:
print(classification_report(y_test, y_pred_pca, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.81      0.74      0.77       174

   micro avg       0.81      0.74      0.77       174
   macro avg       0.40      0.37      0.39       174
weighted avg       0.81      0.74      0.77       174



C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\OMEN\anaconda3\lib\site-packages\sklearn\metrics\_classif

In [41]:
print(confusion_matrix(y_test, y_pred_pca))

[[129  45   0   0   0]
 [ 30 195  13   0   0]
 [  1  62  30   4   0]
 [  0  29  19  15   0]
 [  0  10   8  10   0]]
